const TOPICS=[
{id:1,t:"Gerenciamento de Usuários",obj:["1.1 Roles necessárias para acessar recursos do console","1.2 Criar roles e atribuir usuários","1.3 Gerenciar API keys"],
key:["Acesso é controlado por roles (RBAC); aplique o menor privilégio.","Apenas Falcon Administrator inicia trials na Store, aprova pedidos, atualiza apps e pausa/remove acesso de apps parceiros.","API clients criados pela Store levam [Store] no nome e não devem ser editados.","Use API clients com escopos mínimos (read/write por recurso) e revise-os periodicamente."],
how:["Host setup and management > User management: criar usuário, atribuir roles.","Support and resources > Resources and tools > API clients and keys: criar cliente, escolher escopos, guardar o secret (exibido uma vez).","Filtre a lista de usuários por role para achar os Falcon Administrators."],
study:"Monte uma matriz role x tarefa (ex.: quem cria exclusões, quem usa RTR, quem gerencia Store)."},
{id:2,t:"Implantação de Sensor",obj:["2.1 Pré-requisitos de instalação por SO","2.2 Analisar políticas default e boas práticas","2.3 Desinstalar sensor","2.4 Troubleshooting"],
key:["Requer CID (com checksum), conectividade com a cloud CrowdStrike e SO suportado.","Uninstall protection: só desinstala/atualiza com maintenance token.","Mantenha sensores em N-2 ou mais novos; atualize mensalmente e teste antes.","Sensor update policy: Auto - N-1, Auto - N-2, versão específica ou updates off."],
how:["Support and resources > Sensor downloads: baixar instalador e copiar o CID.","Configuration > Sensor update policies: criar política e atribuir a host groups.","Para desinstalar com proteção: obter o maintenance token do host no console."],
study:"Pratique instalar em VM Windows e Linux e ler os logs de instalação."},
{id:3,t:"Gerenciamento de Hosts",obj:["3.1 Filtros na página Host Management","3.2–3.3 Desabilitar detecções e seus efeitos","3.4–3.5 RFM: impacto, causas e localizar hosts","3.6–3.7 Sensores inativos e retenção","3.8 Relatórios de hosts"],
key:["Host inativo = status Offline; sem ação, é removido do console após 45 dias (padrão).","Hosts ocultados/excluídos permanecem visíveis por 90 dias.","Host retention policies ocultam/excluem hosts inativos automaticamente.","RFM é um modo seguro por kernel/configuração não suportados (Windows/Linux); a proteção fica reduzida.","Disable detections (menu Actions no painel do host) serve p/ hosts de teste; o sensor deixa de gerar detecções."],
how:["Host setup and management > Host management: filtre por status, plataforma, RFM, Last seen, grupo.","Painel do host > Actions > Disable detections.","Use a coluna Last seen para achar sensores inativos."],
study:"Crie filtros salvos: 'RFM = Sim' e 'Last seen > 30 dias'."},
{id:4,t:"Criação de Grupos",obj:["4.1 Grupo apropriado e impacto nas políticas","4.2 Boas práticas de host groups"],
key:["Políticas são atribuídas a grupos, nunca a hosts individuais.","Dinâmicos: regras por tag, IP/CIDR, versão de SO, OU do AD, prefixo de hostname; recomendados na maioria dos casos.","Estáticos: manuais; úteis em QA/testes.","Host sem grupo com política usa a política default da plataforma."],
how:["Host setup and management > Host groups > Create group (static/dynamic).","Defina filtros e depois atribua o grupo à política (aba Assigned host groups)."],
study:"Desenhe um mapa: grupos de teste -> piloto -> produção."},
{id:5,t:"Aplicação de Políticas",obj:["5.1 Prevention policy","5.2 Sensor update policy","5.3 Roles, políticas e RTR audit logs","5.4–5.5 Containment policy e exclusões de IP/sub-rede","5.6 Arquivos em quarentena"],
key:["Precedência: 1 é a mais alta; se ela for desabilitada, vale a próxima.","Cada plataforma tem uma policy default; configure-a de forma conservadora.","Containment policy define IPs/sub-redes permitidos para hosts em network containment.","Quarentena: arquivos podem ser visualizados, baixados e liberados por quem tem role adequada.","RTR audit logs registram sessões e comandos."],
how:["Configuration > Prevention policies / Sensor update policies / Containment policies.","Edit precedence para reordenar; aba Assigned host groups para atribuir.","Endpoint security > Quarantined files (ver e liberar)."],
study:"Simule: 3 políticas, 2 grupos, 1 host em ambos -> qual vence?"},
{id:6,t:"Configuração de Regras",obj:["6.1 IOA rules customizadas","6.2 Permitir atividade confiável e tratar falsos positivos","6.3 Configurações de IOC","6.4 Configurações CID-wide (General Settings)"],
key:["Custom IOA monitora comportamento não necessariamente malicioso (processo, linha de comando, arquivo, rede).","Exclusões: ML exclusion e Sensor visibility exclusion têm impactos diferentes; use o escopo mais estreito.","IOC: ação detect, prevent, allow (allowlist) ou block; aplicada por host group.","General settings inclui limitação (throttle) de updates."],
how:["Endpoint security > Custom IOA rule groups > Create rule.","Endpoint security > Exclusions e IOC management.","Support and resources > Resources and tools > General settings."],
study:"Compare ML exclusion x visibility exclusion x IOA exclusion."},
{id:7,t:"Dashboards e Relatórios",obj:["7.1 Relatórios de sensor e casos de uso","7.2 Audit logs e casos de uso"],
key:["Relatórios de sensor: cobertura, versões, hosts inativos, RFM.","Audit logs: atividade de usuários, mudanças de política e RTR.","Para trilha de auditoria da Store, use event dashboards ou streaming API."],
how:["Explore os dashboards de Host setup and management e os audit logs no menu Support and resources.","Agende relatórios recorrentes por e-mail."],
study:"Para cada relatório, escreva a pergunta de negócio que ele responde."},
{id:8,t:"Workflows (Fusion SOAR)",obj:["8.1 Configurar workflows para gatilhos"],
key:["Workflow = gatilho + condições + ações. Exige Workflow Author ou Falcon Administrator.","Plugins da Store (Slack, Teams, PagerDuty, ServiceNow, Jira, Okta, Entra ID, Webhook) viram ações.","Notificações de erro da integração vão por e-mail para até 10 Falcon Administrators.","Webhook: HMAC secret >= 32 caracteres; cabeçalho X-CS-Primary-Signature (HmacSHA256)."],
how:["Fusion SOAR > Workflows > Create workflow.","CrowdStrike Store > app > Configure > Add configuration.","Teste com um gatilho de baixa severidade e um canal Slack."],
study:"Monte: detecção crítica -> Slack + ticket no ServiceNow."}];
const EXAM={dur:90,n:60,info:["Prova: 90 min, 60 questões.","Retake: 48h após a 1ª falha; depois 7 dias.","Validade: 3 anos.","Contestação: em até 3 dias (certification@crowdstrike.com).","Pré-requisito: >= 18 anos e voucher; recomendado 6 meses de Falcon."]};
// [topic, question, [options], correctIndex, explanation]
const TEN=["","User Management","Sensor Deployment","Host Management and Setup","Group Creation","Policy Application","Rules Configuration","Dashboards and Reports","Workflows"];
const Q=[
[1,"Who can start an app trial in the CrowdStrike Store?",["Any user","Falcon Administrator","Falcon Analyst","Dashboard Admin"],1,"Only the Falcon Administrator starts/approves trials; other roles can request them."],
[1,"How many Falcon Administrators are emailed when a user requests an app trial?",["1","Up to 5","Up to 10","All of them"],1,"Up to 5 administrators are notified."],
[1,"A trial request was denied. How long before the same app can be requested again?",["24 hours","3 days","7 days","30 days"],2,"Denied requests reset after 7 days."],
[1,"How are API clients created by partner apps identified?",["API_ prefix","[Store] in the name","-partner suffix","They are not listed"],1,"They include [Store] in the name; do not edit them."],
[1,"When you revoke a partner app's API access, its API client is...",["Disabled","Hidden","Permanently deleted","Unchanged"],2,"Revoking deletes it; pausing only disables it."],
[1,"Which principle should guide role assignment?",["Everyone an administrator","Least privilege","Copy another user's role","A single shared role"],1,"Role-based access control with least privilege."],
[1,"When is an API client's secret displayed?",["Always","Only at creation","By email","After 24 hours"],1,"Store it safely when the client is created."],
[2,"What is required to install the sensor?",["Maintenance token","CID","API key","Host group name"],1,"The installer needs the CID (with checksum)."],
[2,"With uninstall protection enabled, uninstalling requires...",["Local admin only","A maintenance token","Safe mode reboot","Nothing"],1,"Without the maintenance token the sensor cannot be uninstalled."],
[2,"Minimum recommended sensor version?",["N","N-1","N-2 or newer","Any version"],2,"Keep sensors at N-2 or newer."],
[2,"'Auto - N-1' makes the host update to...",["The newest version","The second-newest version","The third-newest version","Stays put"],1,"N-1 is the second-newest version."],
[2,"Which policy controls the sensor version?",["Prevention","Sensor update","Software update","Containment"],1,"The sensor update policy."],
[2,"Do software update policies control the Falcon sensor version?",["Yes","No, only software installed by Store apps","Only on Linux","Only on Mac"],1,"They do not control the sensor."],
[2,"Best practice before rolling out a new sensor version?",["Update everyone at once","Test in a pilot group","Disable updates","Reinstall"],1,"Test internally in a pilot group first."],
[2,"Which value ties the sensor to your Falcon account (CID) during install?",["Maintenance token","CID with checksum","API secret","Group name"],1,"The CID with checksum is passed to the installer."],
[3,"Default time before an inactive host is deleted from the console?",["15 days","30 days","45 days","90 days"],2,"The system default is 45 days."],
[3,"How long do hidden/deleted hosts remain visible?",["7 days","45 days","90 days","Indefinitely"],2,"90 days."],
[3,"An inactive host is one with status...",["Online","Offline","RFM","Contained"],1,"Status Offline; check the Last seen value."],
[3,"What is RFM?",["Maintenance mode","Safe mode for unsupported kernels/configurations","Containment mode","Update mode"],1,"A safe mode that avoids compatibility issues."],
[3,"Where do you disable detections for a host?",["Prevention policy","Actions menu in the host panel","IOC management","Sensor update policy"],1,"Actions > Disable detections."],
[3,"Effect of disabling detections on a host?",["None","No detections are generated","Sensor is uninstalled","Host is isolated"],1,"Useful for test hosts."],
[3,"How can you automate removal of inactive hosts?",["Host retention policy","Containment policy","IOA rule","Manual workflow"],0,"Host retention policies hide/delete inactive hosts."],
[3,"How do you locate inactive sensors?",["Filter by Last seen","By role","By IOC","By exclusion"],0,"Last seen shows inactivity."],
[3,"Most common cause of RFM on Windows hosts?",["Missing CID","Microsoft updates that change the kernel","Uninstall protection","A proxy"],1,"The kernel is not yet certified; the sensor keeps monitoring at reduced capacity."],
[4,"Policies are assigned to...",["Hosts","Host groups","Users","Roles"],1,"Always to host groups."],
[4,"Which is NOT a dynamic group filter?",["Tag","CIDR","AD OU","Logged-in user name"],3,"Filters: tag, IP, OS, OU, hostname, etc."],
[4,"Static groups are best for...",["Static environments (QA/test)","All of production","Nothing","Linux only"],0,"Also when dynamic filters are not enough."],
[4,"A host in no group with an assigned policy uses...",["No policy","The platform default policy","The first policy created","An error state"],1,"It falls back to the default policy."],
[4,"Newly created dynamic groups start...",["Full","Empty until filters are defined","With all hosts","Disabled"],1,"You define filters to populate them."],
[4,"Can an OS upgrade change which policy applies to a host?",["Never","Yes, if it changes dynamic group membership","Only manually","Only on Windows"],1,"A group change can change the policy."],
[5,"In policy precedence, which value is highest?",["1","10","0","Last"],0,"1 is the highest."],
[5,"The highest-precedence policy is disabled. The host...",["Has no policy","Uses the next applicable policy","Always uses default","Errors"],1,"It falls back to the next policy."],
[5,"How should default policies be configured?",["Most aggressive","The most conservative settings you accept","Empty","Disabled"],1,"Conservative settings."],
[5,"A containment policy defines...",["Sensor version","Allowed IPs/FQDNs for contained hosts","ML exclusions","Roles"],1,"IP, DNS and FQDN exceptions for contained hosts."],
[5,"Software update policy requirement?",["Windows + PowerShell 3.0+","Linux","Mac","Any OS"],0,"Windows only, PowerShell 3.0+, and RTR put enabled."],
[5,"Which RTR command must be enabled for software update policies?",["get","put","runscript","kill"],1,"put."],
[5,"Where do you review what was done in RTR sessions?",["RTR audit logs","Prevention policy","Fusion","Discover"],0,"Audit logs > RTR."],
[5,"'Software updates off' means...",["Uninstalls the software","Keeps the current version on each host","Always updates","Blocks the host"],1,"It keeps what is installed."],
[5,"Disabling a software update policy...",["Uninstalls the software","Does not uninstall it","Removes the hosts","Deletes the app"],1,"Use Uninstall software to remove it."],
[5,"How long is an unreleased quarantined file kept on the host?",["7 days","30 days","45 days","90 days"],1,"Deleted from the host after 30 days."],
[6,"Custom IOA rules are used to...",["Detect known malware only","Monitor behavior that is not fundamentally malicious","Change sensor version","Create users"],1,"Custom behavioral monitoring."],
[6,"Possible actions for an IOC?",["Detect/Prevent/Allow/Block","Only Allow","Only Block","None"],0,"Allowlist and blocklist via IOCs."],
[6,"Best practice for exclusions?",["Broadest scope","Narrowest possible scope","Global","No review"],1,"Reduces evasion risk."],
[6,"Where can you throttle how many hosts update at once?",["General settings > Throttle updates","Prevention policy","IOC","Host groups"],0,"Throttle updates tab."],
[6,"False positive on a trusted process. What do you do?",["Disable the sensor","Create a specific exclusion","Delete the host","Disable detections globally"],1,"A specific exclusion."],
[6,"In an ML exclusion, 'Detect/Prevent' does what?",["Generates a normal detection","No detection or block, but events are logged","Uninstalls the sensor","Isolates the host"],1,"Events still reach the cloud, but no detection is generated."],
[6,"IOCs apply to...",["Host groups","Users","Roles","Apps"],0,"Scoped to hosts/groups."],
[7,"An audit log is useful for...",["Seeing who changed a policy","Downloading the sensor","Listing CVEs","Installing apps"],0,"It provides a change trail."],
[7,"Auditing CrowdStrike Store activity uses...",["Event dashboards or the streaming API","Email only","Nothing","IOA rules"],0,"Per the documentation."],
[7,"Sensor reports are useful for...",["Coverage, versions, inactive hosts","IOCs only","Tickets only","Users only"],0,"Sensor hygiene."],
[7,"To review an analyst's commands in RTR...",["RTR audit logs","Sensor report","IOC","Containment"],0,"RTR audit logs."],
[8,"Which role can author workflows?",["Workflow Author or Falcon Administrator","Any user","Read-only","Quarantine Manager"],0,"Per the documentation."],
[8,"Integration error emails go to...",["1 admin","Up to 10 Falcon Administrators","No one","Analysts"],1,"Up to 10."],
[8,"Minimum HMAC key length for a webhook?",["8","16","32 characters","64"],2,"At least 32 characters."],
[8,"Default webhook signature header?",["X-CS-Primary-Signature","Authorization","X-Sig","Auth-CS"],0,"The default value."],
[8,"For new Teams workflows, use...",["The Deprecated app","Microsoft Teams SOAR Actions","Office 365 connector","Email"],1,"The Office 365 connector was retired."],
[8,"ServiceNow CMDB assets appear only if sys_updated_on is within...",["7 days","45 days","90 days","1 year"],1,"The last 45 days."],
[8,"For Slack, what do you generate in Slack?",["An incoming webhook URL","A password","A CID","An RTR token"],0,"Paste the URL into Falcon."],
[8,"How long does a CrowdStrike app trial last?",["7 days","15 days","30 days","60 days"],1,"15 days; it cannot be restarted."],
[8,"Before a production trigger, you should...",["Test with a low-severity scenario","Enable it directly","Skip testing","Delete logs"],0,"Validate first."]];
const DEEP={
1:["Roles relevantes: Falcon Administrator (gestão de usuários, Store), Endpoint Manager (tokens de instalação, ocultar/excluir hosts), Workflow Author (workflows), Falcon Analyst, RTR Read Only Analyst / Active Responder / Administrator.","Roles temporárias: o Falcon Administrator pode conceder privilégios elevados por tempo limitado.","Convite de usuários externos ao CID exige Falcon Administrator.","Ocultar/excluir hosts exige Falcon Administrator, Endpoint Manager ou equivalente."],
2:["Rede: acesso à internet/cloud CrowdStrike, tráfego TLS liberado e sem inspeção HTTPS (o sensor usa certificate pinning; DPI, proxies e firewalls podem quebrar a validação).","Windows: verificar com sc.exe query csagent (deve estar RUNNING). Instalação silenciosa: instalador /install /quiet /norestart CID=<CID com checksum>.","Parâmetros úteis: GROUPING_TAGS=\"tag1,tag2\" (tags disponíveis na 1ª conexão), ProvNoWait=1 (proxy detectado via IE), MAINTENANCE_TOKEN em instalações/atualizações com proteção.","Linux: falconctl -s --cloud={us-1|us-2|eu-1|us-gov-1|us-gov-2} para definir a cloud do CID.","VDI não persistente: hosts domain-joined com FQDN fixo; instale a versão desejada na golden image e trave a sensor update policy nessa versão.","Se o FQDN muda, use a opção de template de VM ou clones vinculados.","Desinstalação: Painel de Controle ou CsUninstallTool.exe MAINTENANCE_TOKEN=<token> /quiet.","Sensor update policy: 'Show early adopter sensor builds' para testar builds antecipados.","Pausar content updates (ex.: Rapid Response) suspende IOA/allowlist/blocklist da CrowdStrike; não é possível pausar pacotes System Critical."],
3:["RFM Windows: o sensor continua monitorando e reportando, mas desconecta de alguns elementos do kernel; alguns padrões de detecção e poucas prevenções deixam de disparar.","RFM Linux: kernel não suportado -> sensor sem detecções/processamento de eventos. RFM Mac: comum quando Full Disk Access não foi concedido; ainda se comunica com a cloud.","Domain controllers (Identity Protection): o sensor pode desligar regras/inspeção de tráfego ao ultrapassar limiares de recursos e gera notificação.","Retenção: sem política de retenção, inativos (Offline) são excluídos em 45 dias; ocultados/excluídos ficam visíveis por 90 dias.","Retention policy só se aplica a hosts que se conectam à cloud após a atribuição; hosts que ficam offline seguem a política anterior/default.","Duplicados/efêmeros: use retention policies com auto-hide/auto-delete.","Migração entre CIDs: jobs de migração no Falcon Flight Control (CID pai)."],
4:["Atributos: IP/CIDR, hostname (ex.: FIN*), OU do AD, Site Name, versão de SO, tags.","Combine filtros (E) para grupos específicos (ex.: OU do departamento + site afetado).","Tags do sensor (sensor grouping tags) x Falcon grouping tags: as do sensor podem ser definidas na instalação.","Exemplos: grupo com hostname FIN* para política restritiva; grupo por sub-rede para desabilitar cloud updates em escritório com pouca banda; tag 'dev' para prevention menos agressiva.","Boa prática: preferir grupos dinâmicos; usar estáticos em ambientes fixos/QA; nomes claros e um grupo por finalidade."],
5:["Precedência funciona igual em prevention, sensor update, containment e retention policies.","Prevention (XUMD): Cautious (alto), Moderate (alto+médio), Aggressive (+baixo), Extra Aggressive (+experimental). Teste em staging; Aggressive só com testes; Extra Aggressive não é para produção.","Conflito com outro software: mova um host de teste para política com XUMD desabilitado, reinicie e retente; abra caso no Support.","Network containment: estados Network Contain, Lift Containment e os pendentes. Falcon Container não suporta contenção de pods.","Containment policy: Host setup and management > Response and containment > Containment policy > Create allowlist. Tipos: IP Range, DNS (Windows sensor 7.33+), FQDN (Windows 7.33+, Mac 7.39+; opção Allow subdomains).","Quarentena: Endpoint security > Monitor > Quarantined files. Liberar afeta só aquele host; para os demais, adicione o arquivo à allowlist global.","RTR audit logs: Audit logs > Audit logs > RTR (sessões, comandos, arquivos com get) e logs de scripts customizados / arquivos 'put'.","Visibilidade: RTR Read Only/Active Responder/Administrator veem só suas sessões; Falcon Administrator vê todas; logs de scripts e 'put' só RTR Administrator e Falcon Administrator."],
6:["Custom IOA: tipos Process Creation, File Creation, Network Connection e Domain Name.","Ações de prevenção: Process Creation = Block execution (Windows/macOS) ou Kill Process (Linux); os demais tipos = Kill Process.","ML exclusions: padrão glob, ou certificado; opcionalmente processo pai/avô (reduz superfície); tipos Detect/Prevent e Upload Files to CrowdStrike; escopo: todos os hosts ou grupos.","ML exclusions não valem para CDFS nem compartilhamentos de rede.","Scans sob demanda: exclusões de caminho aplicam-se só ao scan; caminhos com ** demoram mais.","IOC: use allow/block por hash/domínio/IP; para liberar arquivo em todos os hosts use allowlist global (não apenas liberar da quarentena).","Regra de ouro para falso positivo: exclusão mais específica, no menor escopo de grupos."],
7:["Audit logs de RTR: sessões e scripts/put; úteis em investigação e conformidade.","Use relatórios de sensor para versões (N-2), inativos e RFM; agende entrega recorrente.","Eventos avançados: consulta como #event_simpleName=OdsMaliciousFileFound em Advanced event search."],
8:["Autoria exige Workflow Author ou Falcon Administrator.","Fluxo: gatilho (ex.: detecção) -> condição (severidade, grupo, tipo de dispositivo) -> ação (Slack/Teams/PagerDuty/ServiceNow/Jira/webhook).","Configure o plugin na Store antes de aparecer como ação; use nomes claros para as configurações.","Teams: para novos workflows use Microsoft Teams SOAR Actions."]};
const STUDY=[
["Getting Started with CrowdStrike Products",[
["Learn and Get Support",[
["Learn how to Navigate the Falcon Console","Falcon Management > 1.2.4 Falcon console navigation"],
["Watch the Onboarding Webinar","CrowdStrike University / Support portal (fora dos PDFs)"],
["Subscribe to Tech Alerts and Release Notes","Falcon Management > 1.5 Manage CrowdStrike Tech Alerts"],
["Set Up Falcon Notifications","Falcon Management > 1.8 Falcon Notifications"],
["Falcon 102 course (Platform Onboarding Configuration)","CrowdStrike University"]]],
["Set Up and Deploy Sensors",[
["Add and Manage Users in the Falcon Console","Falcon Management > 1.10.1 User Management e 1.10.2 Role Management"],
["Set up Single Sign-On (SSO)","Falcon Management > 1.13.3 Single Sign-On (SSO) for Falcon (Set up and use SSO)"],
["Prevention Policies Phase 1 - Initial Deployment","Endpoint Security > 1.5.2.21.1 Phase 1: Initial deployment"],
["Deploy Windows Sensors","Sensor Deployment > 1.5.1 Falcon Sensor for Windows Deployment"],
["Deploy Linux Sensors","Sensor Deployment > 1.7.3 Falcon Sensor for Linux"],
["Deploy Mac Sensors","Sensor Deployment > 1.4.1 Falcon Sensor for Mac Deployment"],
["Create Host Groups","Falcon Management > 1.6.3 Managing host groups"],
["Configure Sensor on Golden Images, VM and VDI Templates","Sensor Deployment > 1.5.1.7.7 (VDI, VM template, linked/instant clones)"],
["Set up Sensor Update Policies","Sensor Deployment > 1.1 Sensor Update Policies"],
["Falcon 105 course (Sensor Installation, Configuration and Troubleshooting)","CrowdStrike University; veja também Sensor Deployment > 1.5.1.9 e 1.5.1.10 (Troubleshooting)"]]],
["Additional Features and Best Practices",[
["Manage Your Hosts","Falcon Management > 1.6.2 Managing Hosts"],
["Customize Host Retention Policies","Falcon Management > 1.6.2.5.2 Host retention policies"],
["Create Custom Dashboards and Scheduled Reports","Falcon Management > 1.11.1 Customizable Dashboards e 1.11.2 Scheduled Reports"],
["Keep Track of Usage and Licensing","Falcon Management > seção Billing (procure por 'Billing' / uso de licenças)"],
["Learn about CrowdStrike APIs","CrowdStrike APIs > General Info"],
["Understand Reduced Functionality Mode (RFM)","Sensor Deployment > 1.5.1.15 (Windows), 1.4.1.10 (Mac), 1.7.3.2.3 (Linux)"]]]]],
["Getting Started with Endpoint Detection",[
["Onboarding",[
["Complete the 'Initial Setup' Quick Start Guide","Endpoint Security > 1.1.3 Getting Falcon up and running"],
["Watch the Detection Triage Webinar Recording","CrowdStrike University; leia Endpoint Security > 1.3.2 Endpoint Detection Monitoring"],
["Create Allowlists and Exclusions","Endpoint Security > 1.5.1.2 (Exclusions: ML, IOA, sensor visibility) e IOC management"],
["Prevention Policies Phase 2 - Interim Protection","Endpoint Security > 1.5.2.21.2 Phase 2: Interim protection"],
["Prevention Policies Phase 3 - Optimal Protection","Endpoint Security > 1.5.2.21.3 Phase 3: Optimal protection"],
["Incident Responder Learning Plan","CrowdStrike University"]]],
["Using Endpoint Detection",[
["Learn about Network Containment","Endpoint Security > 1.4.2 Network Containment"],
["Use Real-time Response","Endpoint Security > 1.4.1 Real Time Response (inclui audit logs)"]]],
["Advanced Setup",[
["Use Fusion SOAR to Streamline Workflows","Documentação Fusion SOAR; integrações no PDF CrowdStrike Store > 1.3"]]]]]];
